apiVersion: v2
name: ocis
description: ownCloud Infinite Scale (oCIS) Helm chart
keywords:
  - owncloud
  - ocis
maintainers:
  - name: ownCloud GmbH
    email: devops@owncloud.com
    url: https://owncloud.com
type: application
version: 0.0.0
appVersion: 2.0.0-rc.1
# supported Kubernetes versions
# should only contain non EOL versions from https://kubernetes.io/releases/patch-releases/#non-active-branch-history
# if this changes, also kubernetesVersions in .drone.star needs to be changed
kubeVersion: "~1.23.0 || ~1.24.0 || ~1.25.0 || ~v1.22.15-aliyun"
sources:
  - https://github.com/owncloud/ocis-charts
  - https://github.com/owncloud/ocis
  - https://github.com/cs3org/reva
